run:
  timeout: 5m
  go: "1.21"
  tests: true
  allow-parallel-runners: true

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

linters:
  enable:
    # Default linters
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    # Additional recommended linters
    - bodyclose
    - durationcheck
    - errname
    - errorlint
    - gci
    - gofmt
    - goimports
    - gocritic
    - gosec
    - misspell
    - nolintlint
    - revive
    - rowserrcheck
    - sqlclosecheck
    - unconvert
    - whitespace

linters-settings:
  errcheck:
    check-type-assertions: false
    check-blank: false
    exclude-functions:
      - fmt.Fprintf
      - fmt.Fprintln
      - fmt.Printf
      - fmt.Println
      - (io.Writer).Write

  gci:
    sections:
      - standard
      - default
      - prefix(github.com/ishaan812/devlog)
    skip-generated: true

  gofmt:
    simplify: true
    rewrite-rules:
      - pattern: "interface{}"
        replacement: "any"
      - pattern: "a[b:len(a)]"
        replacement: "a[b:]"

  goimports:
    local-prefixes: github.com/ishaan812/devlog

  gocritic:
    enabled-tags:
      - diagnostic
      - performance
    disabled-checks:
      - hugeParam
      - rangeValCopy
      - ifElseChain
      - appendAssign
      - elseif

  gosec:
    excludes:
      - G104 # Audit errors not checked
      - G304 # File path provided as taint input
      - G306 # Poor file permissions

  misspell:
    locale: US

  nolintlint:
    require-explanation: false
    require-specific: true

  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: increment-decrement
      - name: indent-error-flow
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: var-declaration

  staticcheck:
    checks:
      - all
      - -SA1019 # Ignore deprecated function warnings

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck
    - path: cmd/
      linters:
        - gochecknoinits
    - path: internal/cli/
      linters:
        - errcheck
      text: "Error return value"
    - path: internal/tui/
      linters:
        - errcheck
    - path: internal/git/
      linters:
        - errcheck

  max-issues-per-linter: 50
  max-same-issues: 10
  new: false
