const CLI_COMMANDS = [
  {
    id: 'cmd-root',
    title: 'devlog',
    summary: 'Root command for DevLog.',
    usage: 'devlog [command]',
    params: [
      '--verbose, -v: Enable verbose output',
      '--profile <name>: Use specific profile',
    ],
    examples: ['devlog --verbose ingest', 'devlog --profile work worklog --days 7'],
  },
  {
    id: 'cmd-ingest',
    title: 'devlog ingest',
    summary: 'Ingest git history and index codebase.',
    usage: 'devlog ingest [path]',
    params: [
      '--days <n>: Number of days to ingest (default 30)',
      '--all: Ingest full git history',
      '--since <YYYY-MM-DD>: Ingest commits since date',
      '--branches <b1,b2>: Specific branches',
      '--all-branches: Ingest all branches without prompt',
      '--reselect-branches: Ignore saved branch selection',
      '--skip-summaries: Skip LLM summaries',
      '--skip-commit-summaries: Skip commit summaries',
      '--fill-summaries: Fill missing summaries',
      '--git-only: Only ingest git history',
      '--index-only: Only index codebase',
      '--max-files <n>: Override indexing limit',
      '--all-files: Index all files',
      '--force-reindex: Reindex ignoring hashes',
      '--skip-worklog: Skip worklog prompt',
      '--auto-worklog: Automatically generate worklog after ingest',
      '--reselect-folders: Re-prompt indexed folders',
    ],
    examples: ['devlog ingest', 'devlog ingest ~/projects/myapp --days 90'],
  },
  {
    id: 'cmd-cron',
    title: 'devlog cron',
    summary: 'Set up a daily ingest + worklog cron job with confirmation.',
    usage: 'devlog cron [path]',
    params: [
      '--hour <0-23>: Hour of day to run (default 9)',
      '--minute <0-59>: Minute of hour (default 0)',
      '--days <n>: Ingest window in days per run (default 1)',
      '--log <path>: Optional cron output log file',
      '--yes, -y: Skip confirmation prompt',
      '--dry-run: Print cron entry without installing',
    ],
    examples: [
      'devlog cron                                   # prompts before install',
      'devlog cron ~/projects/myapp --hour 7 --minute 30 --days 1',
      'devlog cron --yes',
      'devlog cron --dry-run',
    ],
  },
  {
    id: 'cmd-cron-remove',
    title: 'devlog cron remove',
    summary: 'Remove scheduled DevLog cron jobs (single repo or all).',
    usage: 'devlog cron remove [path]',
    params: [
      '--all: Remove all DevLog-managed cron jobs',
      '--yes, -y: Skip confirmation prompt',
    ],
    examples: [
      'devlog cron remove',
      'devlog cron remove ~/projects/myapp',
      'devlog cron remove --all',
    ],
  },
  {
    id: 'cmd-worklog',
    title: 'devlog worklog',
    summary: 'Generate markdown work logs.',
    usage: 'devlog worklog',
    params: [
      '--days <n>: Number of days (default 7)',
      '--output, -o <file>: Output path',
      '--provider <name>: LLM provider override',
      '--model <name>: LLM model override',
      '--no-llm: Skip LLM summaries',
      '--branch <name>: Filter by branch',
      '--all: Include all commits',
      '--group-by <date|branch>: Grouping mode',
      '--no-cache: Regenerate cached summaries',
      '--style <technical|non-technical>: Style override',
    ],
    examples: ['devlog worklog --days 14 --group-by branch', 'devlog worklog --style technical -o reports/week.md'],
  },
  {
    id: 'cmd-export',
    title: 'devlog export',
    summary: 'Export cached worklogs.',
    usage: 'devlog export [subcommand]',
    params: [
      'obsidian: Export to Obsidian vault',
      'obsidian status: Show export coverage and pending diffs',
      'obsidian config: Show/update saved export settings',
      'obsidian --vault <path>: Obsidian vault path',
      'obsidian --repo <path>: Repo to export from (default .)',
      'obsidian --root <folder>: Root folder inside vault',
      'obsidian --dry-run: Preview export without writes',
      'obsidian --force: Rewrite all entries',
    ],
    examples: ['devlog export obsidian --vault ~/Obsidian/work', 'devlog export obsidian status --repo ~/projects/frontend'],
  },
  {
    id: 'cmd-configure',
    title: 'devlog configure',
    summary: 'Update DevLog configuration.',
    usage: 'devlog configure',
    params: ['--legacy: Use legacy text-based configuration'],
    examples: ['devlog configure', 'devlog configure --legacy'],
  },
  {
    id: 'cmd-onboard',
    title: 'devlog onboard',
    summary: 'Initial onboarding wizard.',
    usage: 'devlog onboard',
    params: ['--legacy: Use legacy text-based setup'],
    examples: ['devlog onboard'],
  },
  {
    id: 'cmd-list',
    title: 'devlog list',
    summary: 'List profiles and repos.',
    usage: 'devlog list [profiles|repos]',
    params: ['profiles: List only profiles', 'repos: List repos in current profile'],
    examples: ['devlog list', 'devlog list repos'],
  },
  {
    id: 'cmd-commit',
    title: 'devlog commit',
    summary: 'Generate commit message from git diff.',
    usage: 'devlog commit',
    params: [
      '--staged-only, -s: Analyze only staged changes',
      '--provider <name>: LLM provider override',
      '--model <name>: LLM model override',
    ],
    examples: ['devlog commit', 'devlog commit --staged-only'],
  },
  {
    id: 'cmd-console',
    title: 'devlog console',
    summary: 'Open interactive terminal UI.',
    usage: 'devlog console',
    params: [],
    examples: ['devlog console'],
  },
  {
    id: 'cmd-update',
    title: 'devlog update',
    summary: 'Update binary to latest release.',
    usage: 'devlog update',
    params: [],
    examples: ['devlog update'],
  },
  {
    id: 'cmd-profile',
    title: 'devlog profile',
    summary: 'Manage profiles and profile settings.',
    usage: 'devlog profile [subcommand]',
    params: [
      'list: List all profiles',
      'create <name> [description]: Create profile',
      'use <name>: Switch profile',
      'delete <name>: Delete profile',
      'delete <name> --data: Delete profile + DB',
      'repos: List repos in active profile',
      'set-worklog-style <technical|non-technical>: Set style',
    ],
    examples: ['devlog profile create work "Work projects"', 'devlog profile use work'],
  },
  {
    id: 'cmd-models',
    title: 'devlog models',
    summary: 'Manage LLM model/provider configuration.',
    usage: 'devlog models [list|set]',
    params: [
      'set --provider <name>: Set provider',
      'set --model <name>: Set model',
      'set --api-key <key>: Set API key',
      'set --global: Apply to all profiles',
    ],
    examples: ['devlog models list', 'devlog models set --provider anthropic --model claude-sonnet-4-20250514'],
  },
  {
    id: 'cmd-clear',
    title: 'devlog clear',
    summary: 'Clear profile database data.',
    usage: 'devlog clear',
    params: [
      '--force, -f: Skip confirmation',
      '--profile <name>: Clear specific profile',
    ],
    examples: ['devlog clear --force', 'devlog clear --profile work --force'],
  },
  {
    id: 'cmd-branch',
    title: 'devlog branch',
    summary: 'Manage indexed branch metadata.',
    usage: 'devlog branch [subcommand]',
    params: [
      '--codebase <path>: Target codebase path',
      'list: List branches',
      'show [name]: Show branch details',
      'story <name> --message, -m <text>: Set branch story',
      'set-default <name>: Set default branch',
    ],
    examples: ['devlog branch show feature/auth', 'devlog branch set-default main'],
  },
  {
    id: 'cmd-completion',
    title: 'devlog completion',
    summary: 'Generate shell completion scripts.',
    usage: 'devlog completion <bash|zsh|fish|powershell>',
    params: ['<shell>: bash, zsh, fish, powershell'],
    examples: ['devlog completion zsh > "${fpath[1]}/_devlog"'],
  },
]

export const DOC_SECTIONS = [
  {
    id: 'introduction',
    title: 'Introduction',
    summary: 'DevLog is a local-first CLI that turns git history into structured work logs.',
    body: [
      'DevLog helps you stop context-switching fatigue by generating high-signal summaries from commits.',
      'You can ingest multiple repos, track multiple branches, and export markdown summaries to Obsidian.',
      'Everything is designed to stay minimal and practical for daily developer workflows.',
    ],
    code: ['devlog ingest', 'devlog worklog --days 7', 'devlog export obsidian'],
  },
  {
    id: 'installation-instructions',
    title: 'Installation Instructions',
    summary: 'Install with npm, Go, or from source.',
    body: [
      'Use npm for the quickest setup.',
      'Use go install if you prefer Go-native tooling.',
      'From source is ideal for local development and contributions.',
    ],
    code: [
      'npm install -g @ishaan812/devlog',
      'go install github.com/ishaan812/devlog/cmd/devlog@latest',
      'git clone https://github.com/ishaan812/devlog && cd devlog && make install',
    ],
  },
  {
    id: 'quickstart-guide',
    title: 'Quickstart Guide',
    summary: 'From zero to first worklog in a few commands.',
    body: [
      'Run onboarding once to configure provider and profile.',
      'Ingest your repos, then generate and export worklogs.',
      'Use console to browse timeline entries interactively.',
    ],
    code: [
      'devlog onboard',
      'devlog ingest ~/projects/frontend',
      'devlog worklog --days 7',
      'devlog export obsidian --vault ~/Obsidian/work',
      'devlog console',
    ],
  },
  {
    id: 'cli-documentation',
    title: 'CLI Documentation',
    summary: 'Complete CLI command and parameter reference.',
    body: ['All commands below are sourced from the current CLI implementation.'],
    commands: CLI_COMMANDS,
    code: ['devlog --help'],
  },
]
